services:
  # PHP Backend
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ..:/workspaces:cached
    environment:
      - DB_HOST=db
    depends_on:
      - db

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    ports:
      - "3306:3306"


  # React Frontend (Node.js)
  frontend:
    image: node:18-bullseye
    volumes:
      - ..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done" # Keeps container alive

